{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red118\green118\blue118;
\red233\green233\blue220;\red204\green195\blue98;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\cssrgb\c100000\c100000\c100000;\cssrgb\c53725\c53725\c53725;
\cssrgb\c92941\c92941\c89020;\cssrgb\c83922\c80000\c45882;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf2 \cb3 \expnd0\expndtw0\kerning0
# Java Gradle CircleCI 2.0 configuration file\
#\
# Check https://circleci.com/docs/2.0/language-java/ for more details\
#\
\pard\pardeftab720\partightenfactor0
\cf2 version: 2\
jobs:\
  build:\
    docker:\
      # specify the version you desire here\
      - image: circleci/openjdk:8-jdk\
\
      # Specify service dependencies here if necessary\
      # CircleCI maintains a library of pre-built images\
      # documented at https://circleci.com/docs/2.0/circleci-images/\
      # - image: circleci/postgres:9.4\
\
    working_directory: ~/repo\
\
    environment:\
      # Customize the JVM maximum heap limit\
      JVM_OPTS: -Xmx3200m\
      TERM: dumb\
\
    steps:\
      - checkout\
\
      # Download and cache dependencies\
      - restore_cache:\
          keys:\
            - v1-dependencies-\{\{ checksum "build.gradle" \}\}\
            # fallback to using the latest cache if no exact match is found\
            - v1-dependencies-\
\
      - run: gradle dependencies\
\
      - save_cache:\
          paths:\
            - ~/.gradle\
          key: v1-dependencies-\{\{ checksum "build.gradle" \}\}\
\
      # run tests!\
      - run: gradle test}