# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :build do
    gradle(task: "clean assembleDebug")
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to Firebase Distribute Application" 
  lane :deploy_firebase do |options|
    firebase_app_distribution(
      app: "1:342791951911:android:fe9b6c70e1d1ba14672002",
      testers: "sgaikwad@byndr.com, sivaram@byndr.com, kchandana@byndr.com",
      groups: "qa-team",
      apk_path: "app/build/outputs/apk/debug/app-debug.apk",
      firebase_cli_path: $FIREBASE_CLI_PATH
    ) 
  end
end
